apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp-deployment
  labels:
    app: angularapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angularapp
  template:
    metadata:
      labels:
        app: angularapp
    spec:
      containers:
        - name: foodcatalogue
          image: kirsing123/angular-app:v1.0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angularapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80