apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeserver-deployment
  labels:
    app: edgeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgeserver
  template:
    metadata:
      labels:
        app: edgeserver
    spec:
      containers:
        - name: edgeserver
          image: kirsing123/edgeserver:v1.0
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: GATEWAY_APPLICATION_NAME
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: edgeserver
spec:
  selector:
    app: edgeserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072