apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcatalogue-deployment
  labels:
    app: foodcatalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodcatalogue
  template:
    metadata:
      labels:
        app: foodcatalogue
    spec:
      containers:
        - name: foodcatalogue
          image: kirsing123/food-catalogue:v1.0.0
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: FOOD_CATALOGUE_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: postgresql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: postgresql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: foodcataloguedb_url
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: foodcatalogue
spec:
  selector:
    app: foodcatalogue
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001