apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: kirsing123/orders:v1.0.3
          ports:
            - containerPort: 9094
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djdk.tls.client.protocols=TLSv1.2"
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: ORDERS_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: orderdb_url
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "orderdb"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094